In [1]:
data_matrix <- matrix(c(100, 0.8, 200, 1.2, 300, 1.7), nrow = 3, byrow = TRUE)
scaled <- scale(data_matrix)
print(scaled)

     [,1]        [,2]
[1,]   -1 -0.96098765
[2,]    0 -0.07392213
[3,]    1  1.03490978
attr(,"scaled:center")
[1] 200.000000   1.233333
attr(,"scaled:scale")
[1] 100.000000   0.450925


In [2]:
transformation <- matrix(c(1, 0, 0, -1), nrow=2)
result <- scaled %*% transformation
print(result)

     [,1]        [,2]
[1,]   -1  0.96098765
[2,]    0  0.07392213
[3,]    1 -1.03490978


In [3]:
m <- matrix(c(200, 1.5, 180, 1.3, 160, 1.1), nrow=3, byrow=TRUE)
scaled <- scale(m)
print(scaled)

# Flip the temperature column
flip <- matrix(c(1, 0, 0, -1), nrow=2)
result <- scaled %*% flip
print(result)

     [,1] [,2]
[1,]    1    1
[2,]    0    0
[3,]   -1   -1
attr(,"scaled:center")
[1] 180.0   1.3
attr(,"scaled:scale")
[1] 20.0  0.2
     [,1] [,2]
[1,]    1   -1
[2,]    0    0
[3,]   -1    1
