In [4]:
# Create a vector
v <- c(1, 10, 15, 5, 25)
print(v)

[1]  1 10 15  5 25


In [7]:
m <- matrix(1:6, nrow=2, ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [8]:
m[2,3]

[1] 6

In [9]:
m[1,2] <- 99 #Replaces the value in the the 1st row, 2nd column
print(m)

     [,1] [,2] [,3]
[1,]    1   99    5
[2,]    2    4    6


In [12]:
a <- matrix(c(1, 2, 3, 4), nrow=2)
b <- matrix(c(2, 0, 1, 9), nrow=2)
result <- a %*% b
print(result)

     [,1] [,2]
[1,]    2   28
[2,]    4   38


In [1]:
#Original
a <- matrix(c(1, 2, 3, 4), nrow=2)
b <- matrix(c(2, 0, 1, 3), nrow=2)

result <- a %*% b
print(result)

     [,1] [,2]
[1,]    2   10
[2,]    4   14
